[project]
name = "arknights-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=5.3.1",
    "openai>=1.65.2",
]
